name: CI

on: push

jobs:
  test:
    runs-on: macos-11
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: brew bundle
        run: brew bundle
        env:
          CI: true

      - name: check
        run: |
          mas version
          ls ~/Applications
