name: CI

on: push

jobs:
  test:
    runs-on: macos-11
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: brew install
        run: brew bundle --file Brewfiles/Brewfile
        env:
          CI: true

      - name: cask install
        run: brew bundle --file Brewfiles/Caskfile
        env:
          CI: true

      - name: check
        run: |
          mas version
          ls /Applications
